@tool
class_name SMgrDataEditor
extends DebouncedResource

# ------------- [Signal] -------------
## Signal emitted when the state of the dirty flag (unsaved changes) changes
## @param dirty Current dirty state
signal on_dirty_flag_changed(dirty: bool)

# ------------- [Constants] -------------
const _C = preload("uid://c3vvdktou45u")
const DFileWatcher := preload("res://addons/scene_manager/util/file_watcher.gd")
const _DEBOUNCE_TIME = 0.15
## Header text for the autogenerated scene data file
const _SCENE_DATA_HEADER: String = """#
# This file is autogenerated by the Scene Manager plugin.
# DO NOT EDIT.
#
@tool
class_name ScenesClass
extends Node

"""

# ------------- [Private Variable] -------------
var _data: SMgrData
var _log: DLoggerClass
var _file_watcher: DFileWatcher

var _dirty_flag: bool = false:
	set(value):
		if _dirty_flag != value:
			_dirty_flag = value
			on_dirty_flag_changed.emit.call_deferred(value)
	get():
		return _dirty_flag


# ------------- [Callbacks] -------------
func _init(p_data: SMgrData, ebus: SMgrEbusEditor, p_log: DLoggerClass) -> void:
	assert(Engine.is_editor_hint(), "Editor-Only class")
	if p_data == null:
		push_error("SMgrDataEditor: SMgrData instance is required.")
		return

	_data = p_data
	_log = p_log

	# Initialize the debouncer inherited from DebouncedResource
	_init_debouncer(_DEBOUNCE_TIME)

	# Detect changes on the SMgrData side and update its own signals and dirty flag
	_data.changed.connect(_on_data_changed)
	_data.data_changed_debounced.connect(_on_data_changed)
	_setup_filesystem_monitoring.call_deferred()

	_connect_ebus(ebus)


## Callback triggered when the watched files change
func _on_files_changed(_files: PackedStringArray) -> void:
	sync_with_filesystem()


func _on_data_changed() -> void:
	_dirty_flag = true
	# Trigger the debouncer inherited from DebouncedResource
	emit_changed()


# ------------- [Private Method] -------------
func _setup_filesystem_monitoring() -> void:
	_file_watcher = DFileWatcher.new(null, _get_watch_files)
	_file_watcher.files_changed.connect(_on_files_changed)


func _cleanup_filesystem_monitoring() -> void:
	if _file_watcher:
		_file_watcher.destroy()
		_file_watcher = null


func _get_watch_files() -> PackedStringArray:
	var files := PackedStringArray()
	var includes := _data.get_include_list()
	if includes.is_empty():
		return files

	var fs := EditorInterface.get_resource_filesystem()
	if not fs:
		return files
	var root := fs.get_filesystem()
	if not root:
		return files

	_collect_tscn_files_in_includes(root, includes, files)
	return files


func _collect_tscn_files_in_includes(dir: EditorFileSystemDirectory, includes: Array[String], files: PackedStringArray) -> void:
	var dir_path := dir.get_path()
	var dir_under_include := false
	var include_under_dir := false
	for inc in includes:
		if dir_path.begins_with(inc):
			dir_under_include = true
			break
		if inc.begins_with(dir_path):
			include_under_dir = true

	if not dir_under_include and not include_under_dir:
		return

	# Collect files
	for i in range(dir.get_file_count()):
		var file_path := dir.get_file_path(i)
		if file_path.ends_with(".tscn"):
			if dir_under_include:
				files.append(file_path)
			else:
				# Check if the specific file is an include path (since include paths can be specific files)
				for inc in includes:
					if file_path == inc:
						files.append(file_path)
						break

	# Recurse
	for i in range(dir.get_subdir_count()):
		var subdir := dir.get_subdir(i)
		if subdir:
			_collect_tscn_files_in_includes(subdir, includes, files)


## Registers a scene file based on its UID
## @param full_path Full path to the scene file
## @return Registered UID (even if it already existed)
func register_scene_file(full_path: String) -> int:
	var uid := ResourceLoader.get_resource_uid(full_path)
	if uid == ResourceUID.INVALID_ID:
		_log.warn("  Skipping scene file (no UID assigned): " + full_path)
		return uid

	if _data.get_scene_from_uid(uid) != null:
		return uid

	var base_name: String = full_path.get_file().get_basename()
	var scene_name: String = base_name

	# Handle duplicate names to ensure unique Enum keys
	var existing_names: Array[String] = []
	for s in _data.get_scenes_all():
		existing_names.append(s.name.to_upper())

	var counter: int = 1
	while scene_name.to_upper() in existing_names:
		scene_name = base_name + str(counter)
		counter += 1

	# Initialize new scene data using the factory method
	var new_scene := SMgrDataScene.initialize(scene_name, full_path, uid)
	if new_scene:
		# Register via method (emit_changed is called internally)
		_data.set_scene_data(uid, new_scene)
		return uid

	return ResourceUID.INVALID_ID


## Recursively scans a directory and registers .tscn files
## @param dir_path Path to scan
func _scan_dir_recursive(dir_path: String) -> void:
	var dir: DirAccess = DirAccess.open(dir_path)
	if not dir:
		return

	dir.list_dir_begin()
	var file_name: String = dir.get_next()

	while file_name != "":
		var full_path: String = dir_path.path_join(file_name)

		if dir.current_is_dir():
			if file_name != "." and file_name != "..":
				_scan_dir_recursive(full_path)
		elif file_name.ends_with(".tscn"):
			register_scene_file(full_path)

		file_name = dir.get_next()


## For scanning: Recursively collects UIDs
func _scan_and_collect_uids(dir_path: String, collected_uids: Array[int]) -> void:
	var dir: DirAccess = DirAccess.open(dir_path)
	if not dir:
		return

	dir.list_dir_begin()
	var file_name: String = dir.get_next()
	while file_name != "":
		var full_path: String = dir_path.path_join(file_name)
		if dir.current_is_dir():
			if file_name != "." and file_name != "..":
				_scan_and_collect_uids(full_path, collected_uids)
		elif file_name.ends_with(".tscn"):
			var uid := register_scene_file(full_path)
			if uid != ResourceUID.INVALID_ID:
				_log.debug("Found scene: %s (UID: %d)" % [file_name, uid])
				collected_uids.append(uid)
		file_name = dir.get_next()


func _export_scene_enum_string() -> String:
	var lines := PackedStringArray()
	lines.append("enum Id {")
	lines.append("\tNONE = {0},".format([ResourceUID.INVALID_ID]))

	var scenes := _data.get_scenes_all()
	scenes.sort_custom(
		func(a: SMgrDataScene, b: SMgrDataScene) -> bool:
			return a.name.naturalnocasecmp_to(b.name) < 0
	)

	for sc in scenes:
		lines.append("\t{0} = {1},".format([sc.name.to_upper(), sc.uid]))
	lines.append("}\n")
	return "\n".join(lines)


func _export_category_enum_string() -> String:
	var lines := PackedStringArray()
	lines.append("enum CategoryId {")
	var categories := _data.get_categories_list()

	categories.sort_custom(
		func(a: SMgrCategoryData, b: SMgrCategoryData) -> bool:
			return a.name.naturalnocasecmp_to(b.name) < 0
	)

	for c_data in categories:
		var c_uid := c_data.name.hash()
		lines.append("\t{0} = {1},".format([c_data.name.to_upper(), c_uid]))
	lines.append("}")
	return "\n".join(lines)


func _export_utility_functions() -> String:
	return """
## Returns the PackedScene associated with the given Scene ID.
static func get_scene(id: Id) -> PackedScene:
	if id == Id.NONE:
		return null
	var path := ResourceUID.get_id_path(id)
	if path.is_empty():
		return null
	return load(path) as PackedScene


## Returns the file path associated with the given Scene ID.
static func get_scene_path(id: Id) -> String:
	if id == Id.NONE:
		return ""
	return ResourceUID.get_id_path(id)
"""


# ------------- [Public Method] -------------


## Updates the logger instance dynamically
func set_logger(p_log: DLoggerClass) -> void:
	_log = p_log


func get_data() -> SMgrData:
	return _data


func save_data(path: String, data_path: String) -> void:
	# --- write GDScript(Enum) data ---
	var file := FileAccess.open(path, FileAccess.WRITE)
	if not file:
		_log.error("Failed to open file for writing at '%s'." % path)
		return
	file.store_string(_SCENE_DATA_HEADER)
	file.store_string(_export_scene_enum_string())
	file.store_string(_export_category_enum_string())
	file.store_string(_export_utility_functions())
	file.close()

	# --- save this resource itself ---
	_data.sort_data_structures()
	var error := ResourceSaver.save(_data, data_path)
	if error != OK:
		_log.error("Failed to save SMgrData resource at '%s' (Error: %d)." % [data_path, error])
	else:
		_log.info("Successfully saved scene data to: " + path)

	_dirty_flag = false


## Retrieves the current dirty flag
## @return true if there are changes
func get_dirty_flag() -> bool:
	return _dirty_flag


## Changes the display name of a scene
## @param scene_id Scene UID (int)
## @param new_name New display name
func change_scene_name(scene_id: int, new_name: String) -> void:
	var sc := _data.get_scene_from_uid(scene_id)
	if sc:
		if not new_name.is_empty() and sc.name != new_name:
			sc.name = new_name
			# emit_changed is called by the setter of SMgrDataScene itself,
			# which is then detected via SMgrData.


## Removes a specific category assignment from a scene
## @param scene_id Scene UID (int)
## @param category_id ID of the category to remove
func remove_scene_from_category(scene_id: int, category_id: int) -> void:
	if _data.get_category_from_id(category_id) == null:
		return

	var sc := _data.get_scene_from_uid(scene_id)
	if sc:
		var idx := sc.categories.find(category_id)
		if idx != -1:
			sc.categories.remove_at(idx)
			# Direct manipulation of the array does not trigger the setter,
			# so explicit notification is required.
			sc.emit_changed()


## Assigns a scene to a specific category
## @param scene_id Scene UID (int)
## @param category_id ID of the category to assign
func add_scene_to_category(scene_id: int, category_id: int) -> void:
	if _data.get_category_from_id(category_id) == null:
		return

	var sc := _data.get_scene_from_uid(scene_id)
	if sc:
		if not category_id in sc.categories:
			sc.categories.append(category_id)
			sc.emit_changed()


## Removes an include path and unregisters all scenes under it
## @param scene_path Path to remove
func remove_include_path(scene_path: String) -> void:
	var list := _data.get_include_list()
	if list.has(scene_path):
		list.erase(scene_path)
		# emit_changed is called via the setter by property assignment
		_data._include_list = list
	else:
		_log.error("Cannot remove include path. Path '%s' is not in the list." % scene_path)
		return

	var ids_to_remove: Array[int] = []
	for sc in _data.get_scenes_all():
		if sc.path.begins_with(scene_path):
			ids_to_remove.append(sc.uid)

	for sc_id in ids_to_remove:
		_data.remove_scene_data(sc_id)


## Adds a new category (Case-insensitive check)
## @param category_name Name of the category to add
func add_category(category_name: String) -> void:
	var new_name := category_name.strip_edges()
	if new_name.is_empty():
		return

	# Check existing list case-insensitively
	for c_data in _data.get_categories_list():
		if c_data.name.to_lower() == new_name.to_lower():
			_log.warn("Category '%s' already exists." % new_name)
			return

	# Also check for duplicates with default section names
	if new_name.to_lower() == _C.ALL_CATEGORY_NAME.to_lower():
		_log.warn("'%s' is a reserved category name." % new_name)
		return

	var new_data := SMgrCategoryData.new(new_name)
	var category_id := new_name.hash()
	_data.set_category_data(category_id, new_data)


func get_category_id_from_name(category_name: String) -> int:
	for c_data in _data.get_categories_list():
		if c_data.name == category_name:
			return c_data.name.hash()
	return ResourceUID.INVALID_ID


func remove_category(category_id: int) -> void:
	if _data.get_category_from_id(category_id) == null:
		_log.error("Cannot remove category ID '%d'." % category_id)
		return

	_data.remove_category_data(category_id)

	for sc in _data.get_scenes_all():
		if category_id in sc.categories:
			sc.categories.erase(category_id)
			sc.emit_changed()


## Adds an include path and scans the target directory or file
## @param inc_path Path to add
## @return true if successful
func add_include_path(inc_path: String) -> bool:
	var is_dir := DirAccess.dir_exists_absolute(inc_path)
	var is_file := FileAccess.file_exists(inc_path) and inc_path.ends_with(".tscn")

	if not is_dir and not is_file:
		_log.warn("Path '%s' is not a valid directory or .tscn file." % inc_path)
		return false

	# Check for inclusion relationships
	var list := _data.get_include_list()
	for existing_path in list:
		if inc_path.begins_with(existing_path):
			_log.warn("Path '%s' is already covered by '%s'." % [inc_path, existing_path])
			return false

	# If the new path is a parent of existing paths, remove those sub-paths
	var original_size := list.size()
	list = list.filter(func(p: String) -> bool: return not p.begins_with(inc_path))

	if list.size() < original_size:
		_log.info("Removed sub-paths covered by '%s'." % inc_path)

	list.append(inc_path)
	_data._include_list = list  # Triggers setter

	if is_dir:
		_scan_dir_recursive(inc_path)
	else:
		register_scene_file(inc_path)

	_log.info("Successfully added path '%s'." % inc_path)
	return true


## Rescans registered include paths, removes non-existent scenes, and registers new scenes
##
## Scan all registered include paths to find current .tscn files and update UIDs.
## Then, compare the found UIDs with the existing data to prune any scenes
## that no longer exist on the filesystem but are still within the managed paths.
func sync_with_filesystem() -> void:
	_log.debug("Syncing with filesystem...")
	var found_uids: Array[int] = []

	# Collect all current UIDs within the include paths.
	for path in _data.get_include_list():
		if DirAccess.dir_exists_absolute(path):
			_log.debug("  Scanning directory: " + path)
			_scan_and_collect_uids(path, found_uids)
		elif FileAccess.file_exists(path) and path.ends_with(".tscn"):
			_log.debug("  Checking scene file: " + path)
			var uid := register_scene_file(path)
			if uid != ResourceUID.INVALID_ID:
				found_uids.append(uid)

	# Handle path changes for ALL existing scenes (Movement Support)
	# By checking all scenes regardless of found_uids, we can recover paths
	# for scenes that were moved outside of include paths or were manually added.
	for sc in _data.get_scenes_all():
		var current_actual_path := ResourceUID.get_id_path(sc.uid)
		if not current_actual_path.is_empty() and sc.path != current_actual_path:
			_log.info(
				"  Updating path for scene: %s (%s -> %s)" % [sc.name, sc.path, current_actual_path]
			)
			# (SMgrDataScene's setter or emit_changed will trigger the dirty flag)
			sc.path = current_actual_path

	# Remove UIDs that should be under the include list but were not found during the scan
	var uids_to_remove: Array[int] = []
	for sc in _data.get_scenes_all():
		var is_managed := false
		for inc_path in _data.get_include_list():
			if sc.path.begins_with(inc_path):
				is_managed = true
				break

		# If managed but not found on the filesystem, mark for removal
		if is_managed and not sc.uid in found_uids:
			uids_to_remove.append(sc.uid)

	if not uids_to_remove.is_empty():
		for uid in uids_to_remove:
			var sc_data := _data.get_scene_from_uid(uid)
			var sc_name := sc_data.name if sc_data else str(uid)
			_log.info("  Removing missing scene: " + sc_name)
			_data.remove_scene_data(uid)

	_log.debug("Sync complete.")


func cleanup(ebus: SMgrEbusEditor) -> void:
	_disconnect_ebus(ebus)
	# Cleanup debouncer inherited from DebouncedResource
	_cleanup_debouncer()
	# Disconnect the signal
	_cleanup_filesystem_monitoring()


func _connect_ebus(ebus: SMgrEbusEditor) -> void:
	_AF.connect_if_not_connected(ebus.get_dirty_flag, _ebus_get_dirty_flag)
	_data.connect_ebus(ebus)


func _disconnect_ebus(ebus: SMgrEbusEditor) -> void:
	_AF.disconnect_if_connected(ebus.get_dirty_flag, _ebus_get_dirty_flag)
	_data.disconnect_ebus(ebus)


func _ebus_get_dirty_flag(recv: Array[bool]) -> void:
	recv.append(get_dirty_flag())
