@tool
class_name SMgrDataEditor
extends RefCounted

# ------------- [Signal] -------------
## Signal emitted when scene management data changes
signal data_changed
## Signal emitted after changes have settled (no changes for 0.5 seconds)
signal data_changed_debounced
## Signal emitted when the state of the dirty flag (unsaved changes) changes
## @param dirty Current dirty state
signal on_dirty_flag_changed(dirty: bool)


# ------------- [Constants] -------------
## Key constants for parsing within the generated file
class _CommentKey:
	const ENUM: String = "# [Scene Enum]"


const _C = preload("uid://c3vvdktou45u")
const _DEBOUNCER = preload("uid://du3v1b53ukv08")
const _DEBOUNCE_TIME = 0.15
## Header text for the autogenerated scene data file
const _SCENE_DATA_HEADER: String = """#
# This file is autogenerated by the Scene Manager plugin.
# DO NOT EDIT.
#
@tool
extends Node

"""

# ------------- [Private Variable] -------------
var _data: SMgrData

var _dirty_flag: bool = false:
	set(value):
		if _dirty_flag != value:
			_dirty_flag = value
			on_dirty_flag_changed.emit.call_deferred(value)
	get():
		return _dirty_flag

var _data_debouncer: _DEBOUNCER


# ------------- [Callbacks] -------------
func _init(p_data: SMgrData) -> void:
	assert(Engine.is_editor_hint(), "Editor-Only class")
	assert(p_data != null, "SMgrData instance is required")

	_data = p_data
	_init_debouncer()
	data_changed.connect(_on_data_changed)
	_setup_filesystem_monitoring.call_deferred()


## Callback triggered when the filesystem changes (file added, removed, moved, etc.)
func _on_filesystem_changed() -> void:
	sync_with_filesystem()


func _on_data_changed() -> void:
	_dirty_flag = true
	_data_debouncer.call_debounced()


func _on_debounce_timeout() -> void:
	data_changed_debounced.emit()


# ------------- [Private Method] -------------
func _init_debouncer() -> void:
	_data_debouncer = _DEBOUNCER.new()
	_data_debouncer.delay = _DEBOUNCE_TIME
	_data_debouncer.timeout.connect(_on_debounce_timeout)

	# Needs to be attached to the runtime or the editor's main window, etc.
	# Here, we adjust it to be added via Engine.get_main_loop()
	# or check for its existence during the call.
	var tree := Engine.get_main_loop() as SceneTree
	if tree:
		tree.root.add_child.call_deferred(_data_debouncer)


func _setup_filesystem_monitoring() -> void:
	var fs := EditorInterface.get_resource_filesystem()
	if not fs.filesystem_changed.is_connected(_on_filesystem_changed):
		fs.filesystem_changed.connect(_on_filesystem_changed)


func _cleanup_filesystem_monitoring() -> void:
	var fs := EditorInterface.get_resource_filesystem()
	if fs.filesystem_changed.is_connected(_on_filesystem_changed):
		fs.filesystem_changed.disconnect(_on_filesystem_changed)


## Registers a scene file based on its UID
## @param full_path Full path to the scene file
## @return Registered UID (even if it already existed)
func _register_scene_file(full_path: String) -> int:
	var uid := ResourceLoader.get_resource_uid(full_path)
	if uid == ResourceUID.INVALID_ID or _data._scenes.has(uid):
		return uid

	var base_name: String = full_path.get_file().get_basename()
	var scene_name: String = base_name

	# Handle duplicate names to ensure unique Enum keys
	var existing_names: Array[String] = []
	for s in _data._scenes.values():
		existing_names.append(s.name.to_upper())

	var counter: int = 1
	while scene_name.to_upper() in existing_names:
		scene_name = base_name + str(counter)
		counter += 1

	# Initialize new scene data using the factory method
	var new_scene := SMgrDataScene.initialize(scene_name, full_path, uid)
	if new_scene:
		_data._scenes[uid] = new_scene
		data_changed.emit()
		return uid

	return ResourceUID.INVALID_ID


## Recursively scans a directory and registers .tscn files
## @param dir_path Path to scan
func _scan_dir_recursive(dir_path: String) -> void:
	var dir: DirAccess = DirAccess.open(dir_path)
	if not dir:
		return

	dir.list_dir_begin()
	var file_name: String = dir.get_next()

	while file_name != "":
		var full_path: String = dir_path.path_join(file_name)

		if dir.current_is_dir():
			if file_name != "." and file_name != "..":
				_scan_dir_recursive(full_path)
		elif file_name.ends_with(".tscn"):
			_register_scene_file(full_path)

		file_name = dir.get_next()


## For scanning: Recursively collects UIDs
func _scan_and_collect_uids(dir_path: String, collected_uids: Array[int]) -> void:
	var dir: DirAccess = DirAccess.open(dir_path)
	if not dir:
		return

	dir.list_dir_begin()
	var file_name: String = dir.get_next()
	while file_name != "":
		var full_path: String = dir_path.path_join(file_name)
		if dir.current_is_dir():
			if file_name != "." and file_name != "..":
				_scan_and_collect_uids(full_path, collected_uids)
		elif file_name.ends_with(".tscn"):
			var uid := _register_scene_file(full_path)
			if uid != ResourceUID.INVALID_ID:
				collected_uids.append(uid)
		file_name = dir.get_next()


func _export_scene_enum_string() -> String:
	var ret: String = ""
	ret += _CommentKey.ENUM + "\n"
	ret += "enum Id {\n"
	ret += "\tNONE = {0},\n".format([ResourceUID.INVALID_ID])

	for uid in _data._scenes:
		var sc_name := _data._scenes[uid].name
		ret += "\t{0} = {1},\n".format([sc_name.to_upper(), uid])
	ret += "}\n"
	return ret


func _export_category_enum_string() -> String:
	var ret: String = ""
	ret += "enum CategoryId {\n"
	for c_uid in _data._categories:
		var c_data: SMgrCategoryData = _data._categories[c_uid]
		ret += "\t{0} = {1},\n".format([c_data.name.to_upper(), c_uid])
	ret += "}\n"
	return ret


# ------------- [Public Method] -------------
func get_data() -> SMgrData:
	return _data


func save_data(path: String, data_path: String) -> void:
	# --- write GDScript(Enum) data ---
	var file := FileAccess.open(path, FileAccess.WRITE)
	if not file:
		printerr("Scene Manager Error: Failed to open file for writing at '%s'." % path)
		return
	file.store_string(_SCENE_DATA_HEADER)
	file.store_string(_export_scene_enum_string())
	file.store_string(_export_category_enum_string())
	file.close()

	# --- save this resource itself ---
	var error := ResourceSaver.save(_data, data_path)
	if error != OK:
		printerr(
			(
				"Scene Manager Error: Failed to save SMgrData resource at '%s' (Error: %d)."
				% [data_path, error]
			)
		)

	_dirty_flag = false


## Retrieves the current dirty flag
## @return true if there are changes
func get_dirty_flag() -> bool:
	return _dirty_flag


## Changes the display name of a scene
## @param scene_id Scene UID (int)
## @param new_name New display name
func change_scene_name(scene_id: int, new_name: String) -> void:
	if _data._scenes.has(scene_id):
		var sc: SMgrDataScene = _data._scenes[scene_id]
		if not new_name.is_empty() and sc.name != new_name:
			sc.name = new_name
			data_changed.emit()


## Removes a specific category assignment from a scene
## @param scene_id Scene UID (int)
## @param category_id ID of the category to remove
func remove_scene_from_category(scene_id: int, category_id: int) -> void:
	if not _data._categories.has(category_id):
		return

	if _data._scenes.has(scene_id):
		var sc: SMgrDataScene = _data._scenes[scene_id]
		var idx := sc.categories.find(category_id)
		if idx != -1:
			sc.categories.remove_at(idx)
			data_changed.emit()


## Assigns a scene to a specific category
## @param scene_id Scene UID (int)
## @param category_id ID of the category to assign
func add_scene_to_category(scene_id: int, category_id: int) -> void:
	if not _data._categories.has(category_id):
		return

	if _data._scenes.has(scene_id):
		var sc := _data._scenes[scene_id]
		if not category_id in sc.categories:
			sc.categories.append(category_id)
			data_changed.emit()


## Removes an include path and unregisters all scenes under it
## @param scene_path Path to remove
func remove_include_path(scene_path: String) -> void:
	if _data._include_list.has(scene_path):
		_data._include_list.erase(scene_path)
	else:
		printerr(
			(
				"Scene Manager Error: Cannot remove include path. Path '%s' is not in the list."
				% scene_path
			)
		)
		return

	var ids_to_remove: Array[int] = []
	for sc_id in _data._scenes:
		if _data._scenes[sc_id].path.begins_with(scene_path):
			ids_to_remove.append(sc_id)

	for sc_id in ids_to_remove:
		_data._scenes.erase(sc_id)

	data_changed.emit()


## Adds a new category (Case-insensitive check)
## @param category_name Name of the category to add
func add_category(category_name: String) -> void:
	var new_name := category_name.strip_edges()
	if new_name.is_empty():
		return

	# Check existing list case-insensitively
	for c_uid in _data._categories:
		if _data._categories[c_uid].name.to_lower() == new_name.to_lower():
			push_warning("Scene Manager: Category '%s' already exists." % new_name)
			return

	# Also check for duplicates with default section names
	if new_name.to_lower() == _C.ALL_CATEGORY_NAME.to_lower():
		push_warning("Scene Manager: '%s' is a reserved category name." % new_name)
		return

	var new_data := SMgrCategoryData.new(new_name)
	_data._categories[new_data.get_instance_id()] = new_data
	data_changed.emit()


func get_category_id_from_name(category_name: String) -> int:
	for c_uid in _data._categories:
		if _data._categories[c_uid].name == category_name:
			return c_uid
	return ResourceUID.INVALID_ID


func remove_category(category_id: int) -> void:
	if not _data._categories.has(category_id):
		printerr("Scene Manager Error: Cannot remove category ID '%d'." % category_id)
		return

	_data._categories.erase(category_id)

	for sc_id in _data._scenes:
		var scene_info: SMgrDataScene = _data._scenes[sc_id]
		scene_info.categories.erase(category_id)
	data_changed.emit()


## Adds an include path and scans the target directory or file
## @param inc_path Path to add
## @return true if successful
func add_include_path(inc_path: String) -> bool:
	var is_dir := DirAccess.dir_exists_absolute(inc_path)
	var is_file := FileAccess.file_exists(inc_path) and inc_path.ends_with(".tscn")

	if not is_dir and not is_file:
		push_warning(
			"Scene Manager Error: Path '%s' is not a valid directory or .tscn file." % inc_path
		)
		return false

	# Check for inclusion relationships
	for existing_path in _data._include_list:
		if inc_path.begins_with(existing_path):
			push_warning(
				"Scene Manager: Path '%s' is already covered by '%s'." % [inc_path, existing_path]
			)
			return false

	# If the new path is a parent of existing paths, remove those sub-paths
	var original_size := _data._include_list.size()
	_data._include_list = _data._include_list.filter(
		func(p: String) -> bool: return not p.begins_with(inc_path)
	)

	if _data._include_list.size() < original_size:
		print("Scene Manager: Removed sub-paths covered by '%s'." % inc_path)

	# Add to list and execute scan
	_data._include_list.append(inc_path)
	if is_dir:
		_scan_dir_recursive(inc_path)
	else:
		_register_scene_file(inc_path)

	data_changed.emit()
	print("Scene Manager: Successfully added path '%s'." % inc_path)
	return true


## Rescans registered include paths, removes non-existent scenes, and registers new scenes
func sync_with_filesystem() -> void:
	var found_uids: Array[int] = []
	var changed := false

	for path in _data._include_list:
		if DirAccess.dir_exists_absolute(path):
			_scan_and_collect_uids(path, found_uids)
		elif FileAccess.file_exists(path) and path.ends_with(".tscn"):
			var uid := _register_scene_file(path)
			if uid != ResourceUID.INVALID_ID:
				found_uids.append(uid)

	# Remove UIDs that should be under the include list but were not found during the scan
	var uids_to_remove: Array[int] = []
	for uid in _data._scenes:
		var scene_path := _data._scenes[uid].path
		var is_managed := false
		for inc_path in _data._include_list:
			if scene_path.begins_with(inc_path):
				is_managed = true
				break

		# If managed but not found on the filesystem, mark for removal
		if is_managed and not uid in found_uids:
			uids_to_remove.append(uid)

	if not uids_to_remove.is_empty():
		for uid in uids_to_remove:
			_data._scenes.erase(uid)
		changed = true

	# Although data_changed is emitted inside _register_scene_file when a file is added,
	# we emit it here to ensure notification if deletions occurred.
	if changed:
		data_changed.emit()


func cleanup() -> void:
	# Remove debouncer
	# (Because the instance may become invalid when switching between enable/disable of the plugin)
	if is_instance_valid(_data_debouncer):
		_data_debouncer.queue_free()
	# Disconnect the signal
	_cleanup_filesystem_monitoring()
