@tool
class_name SMgrDataEditor
extends DebouncedResource

# ------------- [Signal] -------------
## Signal emitted when the state of the dirty flag (unsaved changes) changes
## @param dirty Current dirty state
signal on_dirty_flag_changed(dirty: bool)

# ------------- [Constants] -------------
const _C = preload("uid://c3vvdktou45u")  # scene_manager_constants.gd
const _DEBOUNCE_TIME = 0.15
## Header text for the autogenerated scene data file
const _SCENE_DATA_HEADER: String = """#
# This file is autogenerated by the Scene Manager plugin.
# DO NOT EDIT.
#
@tool
class_name ScenesClass
extends Node

"""

# ------------- [Private Variable] -------------
var _data: SMgrData
var _log: DLoggerClass
var _watcher: FileEnumWatcher
## True while the file watcher's initial scan is populating _data from the
## filesystem. During this phase we must NOT raise the dirty flag, because
## registering scenes that already exist on disk is not a user-visible edit.
var _initial_load := true

var _dirty_flag: bool = false:
	set(value):
		if _dirty_flag != value:
			_dirty_flag = value
			on_dirty_flag_changed.emit.call_deferred(value)
	get():
		return _dirty_flag


# ------------- [Callbacks] -------------
func _init(p_data: SMgrData, ebus: SMgrEbusEditor, p_log: DLoggerClass) -> void:
	assert(Engine.is_editor_hint(), "Editor-Only class")
	if p_data == null:
		_log.error("SMgrDataEditor: SMgrData instance is required.")
		return

	_data = p_data
	_log = p_log

	# Initialize the debouncer inherited from DebouncedResource
	_init_debouncer(_DEBOUNCE_TIME)

	# Detect changes on the SMgrData side and update its own signals and dirty flag
	_data.changed.connect(_on_data_changed)
	_data.data_changed_debounced.connect(_on_data_changed)
	_setup_filesystem_monitoring.call_deferred()

	_connect_ebus(ebus)


## Called when FileEnumWatcher detects file changes and re-syncs entries
func _on_entries_changed(entries: Array[FEWEntry]) -> void:
	_sync_smgr_data_from_entries(entries)


func _on_data_changed() -> void:
	# Ignore data modifications during the initial watcher scan — these are
	# just registrations of scenes that already exist on disk and should
	# not be treated as user edits.
	if _initial_load:
		return
	_dirty_flag = true
	# Trigger the debouncer inherited from DebouncedResource
	emit_changed()


# ------------- [Private Method] -------------
func _setup_filesystem_monitoring() -> void:
	_watcher = FileEnumWatcher.new(_log)
	_watcher.set_extensions([".tscn"])

	# Register all include paths BEFORE connecting entries_changed.
	# add_include_path() emits entries_changed synchronously, so connecting
	# the signal first would cause _sync_smgr_data_from_entries to fire
	# once per path — each time with only a partial view of all entries,
	# leading to spurious "Removing missing scene" log messages.
	for path in _data.get_include_list():
		_watcher.add_include_path(path)

	# Connect after all paths are registered, then perform a single
	# combined sync so future changes are tracked correctly.
	_watcher.entries_changed.connect(_on_entries_changed)
	_on_entries_changed(_watcher.get_entries())

	# Keep _initial_load true until the debouncer in SMgrData settles.
	# SMgrData inherits a DebouncedResource with DEFAULT_DEBOUNCE_TIME (0.3 s).
	# Any emit_changed() during the scan restarts that timer, so the LAST
	# emit_changed determines when data_changed_debounced fires.
	# We schedule a timer longer than that to ensure the debounced
	# _on_data_changed is also suppressed — otherwise it would re-raise
	# the dirty flag after _initial_load becomes false.
	Engine.get_main_loop().create_timer(1.0).timeout.connect(
		_on_initial_load_complete
	)


func _on_initial_load_complete() -> void:
	_initial_load = false
	# If anything raised the dirty flag during the initial scan through
	# a path other than _on_data_changed, reset it now so the user
	# starts with a clean state.
	if _dirty_flag:
		_dirty_flag = false


func _cleanup_filesystem_monitoring() -> void:
	if _watcher:
		_watcher.destroy()
		_watcher = null


## Converts FEWEntry objects into SMgrDataScene objects and reconciles with _data.
## - New entries are registered as SMgrDataScene via set_scene_data().
## - Existing scenes whose path changed (moved file) are updated.
## - Scenes managed by the include list but absent from entries are removed.
## - New scenes are auto-assigned to categories based on include path mappings.
func _sync_smgr_data_from_entries(entries: Array[FEWEntry]) -> void:
	_log.debug("Syncing SMgrData from watcher entries...")

	var found_uids: Array[int] = []

	for entry in entries:
		found_uids.append(entry.uid)

		var existing := _data.get_scene_from_uid(entry.uid)
		if existing == null:
			# New file — register it, preserving any custom name set previously
			var new_scene := SMgrDataScene.initialize(
				entry.name, entry.path, entry.uid
			)
			if new_scene:
				_data.set_scene_data(entry.uid, new_scene)
				_log.debug("  Registered: %s (%d)" % [entry.name, entry.uid])

				# Auto-assign category based on include path mapping
				_auto_assign_category_to_scene(new_scene)
		else:
			# Existing file — update path if the file was moved
			var actual_path := ResourceUID.get_id_path(entry.uid)
			if not actual_path.is_empty() and existing.path != actual_path:
				_log.info(
					"  Path updated: %s -> %s" % [existing.path, actual_path]
				)
				existing.path = actual_path

	# Remove scenes that are managed but no longer present
	var uids_to_remove: Array[int] = []
	for sc in _data.get_scenes_all():
		var is_managed := false
		for inc_path in _data.get_include_list():
			if sc.path.begins_with(inc_path):
				is_managed = true
				break
		if is_managed and not sc.uid in found_uids:
			uids_to_remove.append(sc.uid)

	for uid in uids_to_remove:
		var sc_data := _data.get_scene_from_uid(uid)
		_log.info(
			(
				"  Removing missing scene: "
				+ (sc_data.name if sc_data else str(uid))
			)
		)
		_data.remove_scene_data(uid)

	_log.debug("Sync complete.")


## Automatically assigns a category to a scene based on include path mappings.
## Finds the longest matching include path and assigns its category.
## @param scene The scene to potentially assign a category to
func _auto_assign_category_to_scene(scene: SMgrDataScene) -> void:
	var best_match_path := ""
	var best_match_length := 0

	# Find the longest matching include path (most specific match)
	for inc_path in _data.get_include_list():
		if scene.path.begins_with(inc_path):
			if inc_path.length() > best_match_length:
				best_match_path = inc_path
				best_match_length = inc_path.length()

	if best_match_path.is_empty():
		return

	var category_id := _data.get_include_path_category(best_match_path)
	if category_id == ResourceUID.INVALID_ID:
		return

	if not category_id in scene.categories:
		scene.categories.append(category_id)
		scene.emit_changed()
		_log.debug(
			(
				"  Auto-assigned category to %s from path '%s'."
				% [scene.name, best_match_path]
			)
		)


func _export_scene_enum_string() -> String:
	var lines := PackedStringArray()
	lines.append("enum Id {")
	lines.append("\tNONE = {0},".format([ResourceUID.INVALID_ID]))

	var scenes := _data.get_scenes_all()
	scenes.sort_custom(SMgrUtil.natural_case_sort)

	for sc in scenes:
		lines.append("\t{0} = {1},".format([sc.name.to_upper(), sc.uid]))
	lines.append("}\n")
	return "\n".join(lines)


func _export_category_enum_string() -> String:
	var lines := PackedStringArray()
	lines.append("enum CategoryId {")
	var categories := _data.get_categories_list()

	categories.sort_custom(SMgrUtil.natural_case_sort)

	for c_data in categories:
		var c_uid := c_data.name.hash()
		lines.append("\t{0} = {1},".format([c_data.name.to_upper(), c_uid]))
	lines.append("}")
	return "\n".join(lines)


func _export_utility_functions() -> String:
	return """
## Returns the PackedScene associated with the given Scene ID.
static func get_scene(id: Id) -> PackedScene:
	if id == Id.NONE:
		return null
	var path := ResourceUID.get_id_path(id)
	if path.is_empty():
		return null
	return load(path) as PackedScene


## Returns the file path associated with the given Scene ID.
static func get_scene_path(id: Id) -> String:
	if id == Id.NONE:
		return ""
	return ResourceUID.get_id_path(id)
"""


# ------------- [Public Method] -------------


## Updates the logger instance dynamically
func set_logger(p_log: DLoggerClass) -> void:
	_log = p_log
	if _watcher:
		_watcher = FileEnumWatcher.new(_log)


func get_data() -> SMgrData:
	return _data


func save_data(path: String, data_path: String) -> void:
	# --- write GDScript(Enum) data ---
	var file := FileAccess.open(path, FileAccess.WRITE)
	if not file:
		_log.error("Failed to open file for writing at '%s'." % path)
		return
	file.store_string(_SCENE_DATA_HEADER)
	file.store_string(_export_scene_enum_string())
	file.store_string(_export_category_enum_string())
	file.store_string(_export_utility_functions())
	file.close()

	# Suppress the watcher so our own write doesn't trigger a re-sync
	if _watcher:
		_watcher.suppress_next_change()

	# --- save this resource itself ---
	_data.sort_data_structures()
	var error := ResourceSaver.save(_data, data_path)
	if error != OK:
		_log.error(
			(
				"Failed to save SMgrData resource at '%s' (Error: %d)."
				% [data_path, error]
			)
		)
	else:
		_log.info("Successfully saved scene data to: " + path)

	_dirty_flag = false


## Retrieves the current dirty flag
## @return true if there are changes
func get_dirty_flag() -> bool:
	return _dirty_flag


## Changes the display name of a scene
## @param scene_id Scene UID (int)
## @param new_name New display name
func change_scene_name(scene_id: int, new_name: String) -> void:
	var sc := _data.get_scene_from_uid(scene_id)
	if sc:
		if not new_name.is_empty() and sc.name != new_name:
			sc.name = new_name
			# emit_changed is called by the setter of SMgrDataScene itself,
			# which is then detected via SMgrData.


## Removes a specific category assignment from a scene
## @param scene_id Scene UID (int)
## @param category_id ID of the category to remove
func remove_scene_from_category(scene_id: int, category_id: int) -> void:
	if _data.get_category_from_id(category_id) == null:
		return

	var sc := _data.get_scene_from_uid(scene_id)
	if sc:
		var idx := sc.categories.find(category_id)
		if idx != -1:
			sc.categories.remove_at(idx)
			# Direct manipulation of the array does not trigger the setter,
			# so explicit notification is required.
			sc.emit_changed()


## Assigns a scene to a specific category
## @param scene_id Scene UID (int)
## @param category_id ID of the category to assign
func add_scene_to_category(scene_id: int, category_id: int) -> void:
	if _data.get_category_from_id(category_id) == null:
		return

	var sc := _data.get_scene_from_uid(scene_id)
	if sc:
		if not category_id in sc.categories:
			sc.categories.append(category_id)
			sc.emit_changed()


## Removes an include path and unregisters all scenes under it
## @param scene_path Path to remove
func remove_include_path(scene_path: String) -> void:
	var list := _data.get_include_list()
	if list.has(scene_path):
		list.erase(scene_path)
		# emit_changed is called via the setter by property assignment
		_data._include_list = list
	else:
		_log.error(
			(
				"Cannot remove include path. Path '%s' is not in the list."
				% scene_path
			)
		)
		return

	if _watcher:
		_watcher.remove_include_path(scene_path)


## Adds a new category (Case-insensitive check)
## @param category_name Name of the category to add
func add_category(category_name: String) -> void:
	var new_name := category_name.strip_edges()
	if new_name.is_empty():
		return

	# Check existing list case-insensitively
	for c_data in _data.get_categories_list():
		if c_data.name.to_lower() == new_name.to_lower():
			_log.warn("Category '%s' already exists." % new_name)
			return

	# Also check for duplicates with default section names
	if new_name.to_lower() == _C.ALL_CATEGORY_NAME.to_lower():
		_log.warn("'%s' is a reserved category name." % new_name)
		return

	var new_data := SMgrCategoryData.new(new_name)
	var category_id := new_name.hash()
	_data.set_category_data(category_id, new_data)


func get_category_id_from_name(category_name: String) -> int:
	for c_data in _data.get_categories_list():
		if c_data.name == category_name:
			return c_data.name.hash()
	return ResourceUID.INVALID_ID


func remove_category(category_id: int) -> void:
	if _data.get_category_from_id(category_id) == null:
		_log.error("Cannot remove category ID '%d'." % category_id)
		return

	_data.remove_category_data(category_id)

	for sc in _data.get_scenes_all():
		if category_id in sc.categories:
			sc.categories.erase(category_id)
			sc.emit_changed()


## Sets the category ID for an include path
## @param path The include path
## @param category_id The category ID to assign (use ResourceUID.INVALID_ID to clear)
func set_include_path_category(path: String, category_id: int) -> void:
	_data.set_include_path_category(path, category_id)


## Retrieves the category ID assigned to an include path
## @param path The include path to check
## @return Category ID (int) or ResourceUID.INVALID_ID if no category assigned
func get_include_path_category(path: String) -> int:
	return _data.get_include_path_category(path)


## Batch assigns a category to all scenes under an include path
## @param path The include path
## @param category_id The category ID to assign
## @return Number of scenes that were assigned
func assign_category_to_include_scenes(path: String, category_id: int) -> int:
	if _data.get_category_from_id(category_id) == null:
		_log.error(
			(
				"Cannot assign category ID '%d' (category does not exist)."
				% category_id
			)
		)
		return 0

	var assigned_count := 0
	for sc in _data.get_scenes_all():
		if sc.path.begins_with(path):
			if not category_id in sc.categories:
				sc.categories.append(category_id)
				sc.emit_changed()
				assigned_count += 1

	_log.info(
		"Assigned category to %d scenes under '%s'." % [assigned_count, path]
	)
	return assigned_count


## Removes a category from all scenes under an include path
## @param path The include path
## @param category_id The category ID to remove
## @return Number of scenes that were affected
func remove_category_from_include_scenes(path: String, category_id: int) -> int:
	var removed_count := 0
	for sc in _data.get_scenes_all():
		if sc.path.begins_with(path):
			var idx := sc.categories.find(category_id)
			if idx != -1:
				sc.categories.remove_at(idx)
				sc.emit_changed()
				removed_count += 1

	if removed_count > 0:
		_log.info(
			(
				"Removed category from %d scenes under '%s'."
				% [removed_count, path]
			)
		)
	return removed_count


## Adds an include path and scans the target directory or file.
## Delegates scanning to the FileEnumWatcher, which emits entries_changed
## when files are found, triggering _on_entries_changed → _sync_smgr_data_from_entries.
## @param inc_path Path to add
## @return true if successful
func add_include_path(inc_path: String) -> bool:
	var is_dir := DirAccess.dir_exists_absolute(inc_path)
	var is_file := (
		FileAccess.file_exists(inc_path) and inc_path.ends_with(".tscn")
	)

	if not is_dir and not is_file:
		_log.warn(
			"Path '%s' is not a valid directory or .tscn file." % inc_path
		)
		return false

	# Check for inclusion relationships
	var list := _data.get_include_list()
	for existing_path in list:
		if inc_path.begins_with(existing_path):
			_log.warn(
				(
					"Path '%s' is already covered by '%s'."
					% [inc_path, existing_path]
				)
			)
			return false

	# If the new path is a parent of existing paths, remove those sub-paths
	var original_size := list.size()
	list = list.filter(
		func(p: String) -> bool: return not p.begins_with(inc_path)
	)

	if list.size() < original_size:
		_log.info("Removed sub-paths covered by '%s'." % inc_path)

	list.append(inc_path)
	_data._include_list = list  # Triggers setter

	# Delegate to watcher — will emit entries_changed → _on_entries_changed
	if _watcher:
		_watcher.add_include_path(inc_path)

	_log.info("Successfully added path '%s'." % inc_path)
	return true


## Rescans registered include paths via the FileEnumWatcher.
func sync_with_filesystem() -> void:
	if _watcher:
		_watcher.sync()


func cleanup(ebus: SMgrEbusEditor) -> void:
	_disconnect_ebus(ebus)
	# Cleanup debouncer inherited from DebouncedResource
	_cleanup_debouncer()
	# Disconnect the signal
	_cleanup_filesystem_monitoring()


func _connect_ebus(ebus: SMgrEbusEditor) -> void:
	_AF.connect_if_not_connected(ebus.get_dirty_flag, _ebus_get_dirty_flag)
	_data.connect_ebus(ebus)


func _disconnect_ebus(ebus: SMgrEbusEditor) -> void:
	_AF.disconnect_if_connected(ebus.get_dirty_flag, _ebus_get_dirty_flag)
	_data.disconnect_ebus(ebus)


func _ebus_get_dirty_flag(recv: Array[bool]) -> void:
	recv.append(get_dirty_flag())
