#
# This file is autogenerated by the Scene Manager plugin.
# DO NOT EDIT.
#
@tool
extends Node

# [Scene Enum]
enum Id \
{ 
	NONE = -1,
	FAKE_LOADING_SCREEN,
	LOADING_SCREEN,
	SCENE_1,
	SCENE_0,
	SCENE_2,
}
