#
# This file is autogenerated by the Scene Manager plugin.
# DO NOT EDIT.
#
@tool
class_name ScenesClass
extends Node

enum Id {
	NONE = -1,
	ADDITIONAL_0 = 4235791306192597837,
	FAKE_LOADING_SCREEN = 5495634729037908381,
	HISTORY_VIEWER = 8019339775020489802,
	LOADING_SCREEN = 3205915700789431932,
	SCENE_0 = 3167048368848614594,
	SCENE_1 = 7784575442615425582,
	SCENE_2 = 5390443888696816947,
	SCENE_BASE = 286306938834776095,
}
enum CategoryId {
}


## Returns the PackedScene associated with the given Scene ID.
static func get_scene(id: Id) -> PackedScene:
	if id == Id.NONE:
		return null
	var path := ResourceUID.get_id_path(id)
	if path.is_empty():
		return null
	return load(path) as PackedScene


## Returns the file path associated with the given Scene ID.
static func get_scene_path(id: Id) -> String:
	if id == Id.NONE:
		return ""
	return ResourceUID.get_id_path(id)
